name: gameconsigne
description: Toko Online Game Store
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^3.1.0
  user_repository:
    path: user_repository
  path: ^1.6.4
  equatable: ^1.0.0
  dio: ^3.0.8
  rxdart: ^0.23.1
  flutter_easyrefresh: ^2.0.8
  flutter_screenutil: ^1.0.2
  event_bus: ^1.1.1
  shared_preferences: ^0.5.6+1
  permission_handler: ^4.2.0+hotfix.2
  html: ^0.14.0+3
  image_picker: ^0.6.3+1
  cookie_jar: ^1.0.1
  path_provider: ^1.5.1
  dio_cookie_manager: ^1.0.0
  sqflite: ^1.2.0
  get_it: ^3.1.0
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0

flutter:
  uses-material-design: true
